Moderate Updates

diff --git a/bin/backup b/bin/backup
--- a/bin/backup
+++ b/bin/backup
@@ -1,7 +1,7 @@
 #!/bin/sh
 # backup	This script is a lite version of our dittodata backup solution
 # Created	2011-12-07 by Dave Henderson (dhenderson@cliquesoft.org)
-# Updated	2026-09-01 by Dave Henderson (dhenderson@cliquesoft.org)
+# Updated	2026-09-02 by Dave Henderson (dhenderson@cliquesoft.org)
 #
 # Unless a valid Cliquesoft Private License (CPLv1) has been purchased for your
 # device, this software is licensed under the Cliquesoft Public License (CPLv2)
@@ -60,6 +60,7 @@
 
 RJN=$(echo "$RANDOM + 2 + $RANDOM" | bc)			# random job number to prevent archive naming conflicts
 DIR_CONF='/etc'
+DIR_KEYS="${USER}/.ssh"
 DIR_LIBS='/lib'
 DIR_LOGS='/var/logs/dittodata'
 DIR_MNTS='/mnt'
@@ -164,7 +165,6 @@ exitGraceful() {
 		rmdir "${TARGET}/${RJN}.t" 2>>"${DIR_LOGS}/${LOG_ERRS}"
 	fi
 
-#	[ $SUCCESS -gt 0 ] && echo "[failed]" >>"${DIR_LOGS}/${LOG_ERRS}"
 	exit $SUCCESS						# exit with the passed error number (for debugging)
 }
 
@@ -394,21 +394,22 @@ for i in "$@"; do						# process each of the passed parameters (after setting de
 	elif ( echo "${i}" | grep -q ^'--source=' ); then
 		SOURCE="${i#*=}"
 	elif ( echo "${i}" | grep -q ^'--source_user=' ); then
-# --user
+# DEV NOTE: it is recommended to use a authentication file for this parameter
 		SOURCE_USER="${i#*=}"
 	elif ( echo "${i}" | grep -q ^'--source_pass=' ); then
-# --pass
+# DEV NOTE: it is recommended to use a authentication file for this parameter
 		SOURCE_PASS="${i#*=}"
 	elif ( echo "${i}" | grep -q ^'--source_domn=' ); then
-# --dom
 		SOURCE_DOMN="${i#*=}"
 	elif ( echo "${i}" | grep -q ^'--source_parm=' ); then
 		SOURCE_PARM="${i#*=}"
 	elif ( echo "${i}" | grep -q ^'--target=' ); then
 		TARGET="${i#*=}"
 	elif ( echo "${i}" | grep -q ^'--target_user=' ); then
+# DEV NOTE: it is recommended to use a authentication file for this parameter
 		TARGET_USER="${i#*=}"
 	elif ( echo "${i}" | grep -q ^'--target_pass=' ); then
+# DEV NOTE: it is recommended to use a authentication file for this parameter
 		TARGET_PASS="${i#*=}"
 	elif ( echo "${i}" | grep -q ^'--target_domn=' ); then
 		TARGET_DOMN="${i#*=}"
@@ -475,8 +476,6 @@ echo -e "           $(date +'%Y-%m-%d  %H:%M:%S')\n" >>"${DIR_LOGS}/${LOG_ERRS}"
 echo -e "${0##*/} $@" >>"${DIR_LOGS}/${LOG_ERRS}"
 
 
-
-
 # variables		NOTE: we can now write to the log
 echo -n "Checking for necessary variable values:" | tee -a "${DIR_LOGS}/${LOG_ERRS}"
 
@@ -529,8 +528,6 @@ else
 
 	# if no custom parameters were passed, then set defaults
 	[ ! "${PARAMETERS}" ] && PARAMETERS="-P --one-file-system --ignore-failed-read --ignore-case -T \"${DIR_TEMP}/${RJN}.list\""
-# REMOVED 2026-08-27 - we aren't doing this any longer
-#	PARAMETERS="--null -T - ${PARAMETERS}"			# indicate we need to read in a files list with null terminators instead of newlines (\n) and that we will read this list from stdin
 
 	[ "${TYPE}" = 'daily' ] && EXT='.d.t'
 	[ "${TYPE}" = 'full' ] && EXT='.f.t'
@@ -556,6 +553,60 @@ echo -n " [source]" | tee -a "${DIR_LOGS}/${LOG_ERRS}"
 [ "${SOURCE_PARM}" ] && SOURCE_PARM=",${SOURCE_PARM}"		# since we are adding a 'ro' prefix, we need to prepend a comma so the syntax is correct
 
 echo " [done]" | tee -a "${DIR_LOGS}/${LOG_ERRS}"
+
+
+
+
+# files
+echo -n "Processing necessary files:" | tee -a "${DIR_LOGS}/${LOG_ERRS}"
+echo -n " [source]" | tee -a "${DIR_LOGS}/${LOG_ERRS}"
+TEMP=
+if [ "${SOURCE:0:2}" = '\\' ]; then
+	echo -n " [cifs]" | tee -a "${DIR_LOGS}/${LOG_ERRS}"
+	TEMP="${DIR_CONF}/$(echo "${SOURCE:2}" | sed 's/\\.*//')"				# store the location along with the isolated hostname as the filename
+	( [ ! "$SOURCE_USER" ] || [ ! "$SOURCE_PASS" ] ) && [ ! -e "${TEMP}" ] && { echo -e " [failure]\nERROR: The SOURCE does not have an authentication file." | tee -a "${DIR_LOGS}/${LOG_ERRS}"; exit 1; }
+elif [ "${SOURCE:0:1}" = '%' ]; then
+	echo -n " [sshfs]" | tee -a "${DIR_LOGS}/${LOG_ERRS}"
+	TEMP=$(echo "${SOURCE:1}" | sed 's/:.*//')						# isolate just the hostname
+	( [ ! "$SOURCE_USER" ] || [ ! "$SOURCE_PASS" ] ) && [ ! -e "${DIR_CONF}/${TEMP}" ] && [ ! -e "${DIR_KEYS}/${TEMP}" ] && { echo -e " [failure]\nERROR: The SOURCE does not have an authentication or identity file." | tee -a "${DIR_LOGS}/${LOG_ERRS}"; exit 1; }
+	[ -e "${DIR_KEYS}/${TEMP}" ] && TEMP= || TEMP="${DIR_CONF}/${TEMP}"			# if there isn't an identity file, then update the variable value so the below code works correctly
+fi
+# if TEMP has a value from one of the two conditions above -AND- an authentication file exists -AND- ...
+if [ "$TEMP" ]; then
+	[ $(stat -c '%u' "${TEMP}") -ne 0 ] && [ $(stat -c '%g' "${TEMP}") -ne 0 ] && { echo -e " [failure]\nERROR: The SOURCE authentication file is not owned by root." | tee -a "${DIR_LOGS}/${LOG_ERRS}"; exit 1; }
+	[ $(stat -c '%a' "${TEMP}") -ne 660 ] && { echo -e " [failure]\nERROR: The SOURCE authentication file does not have 660 permissions." | tee -a "${DIR_LOGS}/${LOG_ERRS}"; exit 1; }
+
+	[ ! "$SOURCE_USER" ] && [ -e "${TEMP}" ] && SOURCE_USER=$(head -1 "${TEMP}")		# store the share username
+	[ ! "$SOURCE_PASS" ] && [ -e "${TEMP}" ] && SOURCE_PASS=$(tail -1 "${TEMP}")		# store the share password
+fi
+
+echo -n " [target]" | tee -a "${DIR_LOGS}/${LOG_ERRS}"
+TEMP=
+if [ "${TARGET:0:2}" = '\\' ]; then
+	echo -n " [cifs]" | tee -a "${DIR_LOGS}/${LOG_ERRS}"
+	TEMP="${DIR_CONF}/$(echo "${TARGET:2}" | sed 's/\\.*//')"
+	( [ ! "$TARGET_USER" ] || [ ! "$TARGET_PASS" ] ) && [ ! -e "${TEMP}" ] && { echo -e " [failure]\nERROR: The TARGET does not have an authentication file." | tee -a "${DIR_LOGS}/${LOG_ERRS}"; exit 1; }
+elif [ "${TARGET:0:1}" = '%' ]; then
+	echo -n " [sshfs]" | tee -a "${DIR_LOGS}/${LOG_ERRS}"
+	TEMP=$(echo "${TARGET:1}" | sed 's/:.*//')
+	( [ ! "$TARGET_USER" ] || [ ! "$TARGET_PASS" ] ) && [ ! -e "${DIR_CONF}/${TEMP}" ] && [ ! -e "${DIR_KEYS}/${TEMP}" ] && { echo -e " [failure]\nERROR: The TARGET does not have an authentication or identity file." | tee -a "${DIR_LOGS}/${LOG_ERRS}"; exit 1; }
+	[ -e "${DIR_KEYS}/${TEMP}" ] && TEMP= || TEMP="${DIR_CONF}/${TEMP}"
+fi
+if [ "$TEMP" ]; then
+	[ $(stat -c '%u' "${TEMP}") -ne 0 ] && [ $(stat -c '%g' "${TEMP}") -ne 0 ] && { echo -e " [failure]\nERROR: The TARGET authentication file is not owned by root." | tee -a "${DIR_LOGS}/${LOG_ERRS}"; exit 1; }
+	[ $(stat -c '%a' "${TEMP}") -ne 660 ] && { echo -e " [failure]\nERROR: The TARGET authentication file does not have 660 permissions." | tee -a "${DIR_LOGS}/${LOG_ERRS}"; exit 1; }
+
+	[ ! "$TARGET_USER" ] && [ -e "${TEMP}" ] && TARGET_USER=$(head -1 "${TEMP}")		# store the share username
+	[ ! "$TARGET_PASS" ] && [ -e "${TEMP}" ] && TARGET_PASS=$(tail -1 "${TEMP}")		# store the share password
+fi
+
+echo " [done]" | tee -a "${DIR_LOGS}/${LOG_ERRS}"
+# DEV NOTE:
+#	- An authentication file is required to mount network & remote shares.
+#	  The format is only two lines, username and password respectively. It		< can supply only one value, but they have to be on the appropriate line (e.g. password on line 2)
+#	  also requires complete root ownership & 660 permissions in DIR_CONF.
+#	alternatively, an sshfs can also have an identity file
+#	both instances require the file to be named the same as the host
 
 
 
@@ -604,10 +655,11 @@ if [ "$TYPE" = 'sync' ]; then
 	# https://unix.stackexchange.com/questions/260616/reuse-rsync-dry-run-output-to-speed-up-the-actual-transfer-later-on
 	echo -n "Obtaining files list to sync:" | tee -a "${DIR_LOGS}/${LOG_ERRS}"
 	( eval "rsync -av --dry-run ${PARAMETERS} \"${DIR_MNTS}/${RJN}.s/\" \"${DIR_MNTS}/${RJN}.t/\"" 2>>"${DIR_LOGS}/${LOG_ERRS}" || {
-		echo -e " [failure]\nERROR: The 'rsync' binary failed in its execution." | tee -a "${DIR_LOGS}/${LOG_ERRS}" -a "${DIR_LOGS}/${LOG_ERRS}"
+		echo -e " [failure]\nERROR: The 'rsync' binary failed in its execution." | tee -a "${DIR_LOGS}/${LOG_ERRS}"
 		echo "Calling: rsync -av --dry-run ${PARAMETERS} \"${DIR_MNTS}/${RJN}.s/\" \"${DIR_MNTS}/${RJN}.t/\"" >>"${DIR_LOGS}/${LOG_ERRS}"
 	} ) | awk '!/^sending incremental file list$/' | awk '/^$/{exit}1' >"${DIR_TEMP}/${RJN}.list"
 	echo " [done]" | tee -a "${DIR_LOGS}/${LOG_ERRS}"
+# LEFT OFF - do we need to do the 'find' code below if --include and --exclude has been passed?
 
 	TEMP=$(cat "${DIR_TEMP}/${RJN}.list" | wc -l)						# store the files-to-be-xferred count for 'pv' below
 	if [ "$TEMP" = '0' ] || [ ! "$TEMP" ]; then						# NOTE: the !TEMP would occur if no files were returned from 'rsync' (e.g. no new data was available yet)
@@ -615,9 +667,9 @@ if [ "$TYPE" = 'sync' ]; then
 		exitGraceful 0
 	else
 		echo "Sync'ing the data..." | tee -a "${DIR_LOGS}/${LOG_ERRS}"
-		( eval "rsync -v --log-file=\"${DIR_LOGS}/${LOG_ERRS}\" --out-format=\"%n\" --include-from=\"${DIR_TEMP}/${RJN}.list\" ${PARAMETERS} \"${DIR_MNTS}/${RJN}.s/\" \"${DIR_MNTS}/${RJN}.t/\"" 2>>"${DIR_LOGS}/${LOG_ERRS}" || {
-			echo "ERROR: The 'rsync' binary failed in its execution." | tee -a "${DIR_LOGS}/${LOG_ERRS}" -a "${DIR_LOGS}/${LOG_ERRS}" 1>&2;
-			echo "Calling: rsync -v --log-file=\"${DIR_LOGS}/${LOG_ERRS}\" --out-format=\"%n\" --include-from=\"${DIR_TEMP}/${RJN}.list\" ${PARAMETERS} \"${DIR_MNTS}/${RJN}.s/\" \"${DIR_MNTS}/${RJN}.t/\"" >>"${DIR_LOGS}/${LOG_ERRS}"
+		( eval "rsync -v --log-file=\"${DIR_LOGS}/${LOG_ERRS}\" --out-format=\"%n\" --include-from=\"${DIR_TEMP}/${RJN}.list\" --delete ${PARAMETERS} \"${DIR_MNTS}/${RJN}.s/\" \"${DIR_MNTS}/${RJN}.t/\"" 2>>"${DIR_LOGS}/${LOG_ERRS}" || {
+			echo "ERROR: The 'rsync' binary failed in its execution." | tee -a "${DIR_LOGS}/${LOG_ERRS}"
+			echo "Calling: rsync -v --log-file=\"${DIR_LOGS}/${LOG_ERRS}\" --out-format=\"%n\" --include-from=\"${DIR_TEMP}/${RJN}.list\" --delete ${PARAMETERS} \"${DIR_MNTS}/${RJN}.s/\" \"${DIR_MNTS}/${RJN}.t/\"" >>"${DIR_LOGS}/${LOG_ERRS}"
 		} ) | pv -w 80 -l -s "$TEMP" >/dev/null
 	fi
 
@@ -674,6 +726,7 @@ else
 	#	we use OFMT to prevent scientific notation from being used	https://stackoverflow.com/questions/12714155/how-can-i-make-awk-not-use-scientific-notation-when-printing-small-values
 	#	the below MUST come in the order presented!
 	if [ "${TYPE}" = 'full' ]; then
+# LEFT OFF - can we do a 'du -hs' here instead of going through every file on the system?
 		cd "${DIR_MNTS}/${RJN}.s/" && eval find ${TEMP%|*}${TEMP#*|} -type f -printf \'%s\\t%p\\n\' 2\>\>\"${DIR_LOGS}/${LOG_ERRS}\" | eval awk \'{print \$2 \>\>\"${DIR_TEMP}/${RJN}.list\"}\; {total += \$1} END {OFMT=\"%.0f\"\; print total \>\>\"${DIR_TEMP}/${RJN}.size\"}\'
 	else
 		# NOTE: we are using SIZE here since TEMP will be filled with 'find' syntax
